[package]
name = "cobbler"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive", "env"] }
humantime = "2.1"
flume = "0.10"
mdns-sd = "0.9"
tabwriter = "1.4"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde_json = "1.0"
